//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanTinCovidAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BANTINCOVIDEntities : DbContext
    {
        public BANTINCOVIDEntities()
            : base("name=BANTINCOVIDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<TINTUC> TINTUC { get; set; }
        public virtual DbSet<TINHHINHCHUNG> TINHHINHCHUNG { get; set; }
        public virtual DbSet<THELOAI> THELOAI { get; set; }
    }
}
