//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanTinCovidAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.TINTUC = new HashSet<TINTUC>();
            this.TINHHINHCHUNG = new HashSet<TINHHINHCHUNG>();
        }
    
        public string MANHANVIEN { get; set; }
        public string CCCD { get; set; }
        public string HOTEN { get; set; }
        public string SODT { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> TrangThaiXoa { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TINTUC> TINTUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TINHHINHCHUNG> TINHHINHCHUNG { get; set; }
    }
}
