//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanTinCovidAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHHINHCHUNG
    {
        public System.DateTime NGAY { get; set; }
        public int CANHIEM { get; set; }
        public int CHUAKHOI { get; set; }
        public int TUVONG { get; set; }
        public string MANHANVIEN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
